name:                MyFirstProject
version:             0.1.0.0

ghc-options: -Wall

dependencies:
  base

library:
  source-dirs: src/
  exposed-modules:
    - Lib
    - Split.LibSplit
  dependencies:
    - split

executables:
  MyFirstProject-exe:
    main:                Main.hs
    source-dirs:         app/
    ghc-options: -Wall -main-is Main
    dependencies:
      MyFirstProject

  new-exec:
    source-dirs: app/
    main: NewExec.hs
    ghc-options: -Wall -main-is NewExec
    dependencies: 
      MyFirstProject

tests:
  MyFirstProject-test:
    main:                Spec.hs
    source-dirs:         test/
    dependencies:
      - MyFirstProject
      - tasty-hunit

